name: sm
services:
  console-sm-admin:
    container_name: 'console-sm-admin'
    env_file:
      - /root/samaritan/env.d/.env.dev.console
    build: 
      dockerfile: ./Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
    expose: 
      - "${SERVICE_PORT}"
    ports:
     - "${HOST_PORT}:${SERVICE_PORT}"
    networks:
      - nginx
networks:
  nginx: 
    external: true