FROM node:alpine
WORKDIR /app

#frontend
ARG FRONTEND=false
ARG REACT_APP_BASE_URL
COPY . .

RUN apk add --update npm
RUN npm install


RUN npm i sass --save-dev
RUN npm run build

RUN npm install -g serve



CMD ["serve", "-s", "build"]